[package]
name = "bandejao-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
teloxide = { version = "0.11", features = ["macros", "auto-send"] }
log = "0.4"
pretty_env_logger = "0.4"
tokio = { version = "1.8", features = ["rt-multi-thread", "macros", "full"] }
serde = { version = "1" }
serde_json = "1"
reqwest = { version = "0.11.12", features = ["json"] }
anyhow = "1"
chrono = "0.4.22"
dotenv = "0.15.0"
cached = "0.39.0"
futures = "0.3.24"
