version: "3.3"

services:
  bandejao-bot:
    build: .
    volumes:
      - .:/app
    environment:
      DATABASE_PASSWORD: mysecret
  db:
    image: postgres
    volumes:
      - ./db/data:/var/lib/postgres/data
    environment:
      POSTGRES_PASSWORD: mysecret
