version: '3.8'

services:
  db:
    container_name: bandejao-bot-db
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=bandejao-bot
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB']
      interval: 10s
      timeout: 5s
      retries: 3
    restart: 'unless-stopped'
