database: &default
    adapter: postgresql
    url: postgres://postgres<%= ":#{ENV['DATABASE_PASSWORD']}" if ENV['DATABASE_PASSWORD'] %>@db/bandejao-bot
    pool: 20

development:
    <<: *default

test:
    <<: *default
    url: postgres://postgres@db/bandejao-bot-test

production:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
